# Generated by Django 5.2.5 on 2025-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfil/defecto/default-avatar.jpg', null=True, upload_to='perfil/'),
        ),
    ]
