# Generated by Django 5.2.5 on 2026-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pass_temporal',
            field=models.BooleanField(default=False),
        ),
    ]
