# Generated by Django 5.2.5 on 2026-03-18 11:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_pass_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfil/defecto/default-avatar.jpg', null=True, upload_to='perfil/'),
        ),
    ]
