# Generated by Django 5.2.5 on 2026-05-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_evolucionpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chat',
            field=models.BooleanField(default=False),
        ),
    ]
