# Generated by Django 5.2.5 on 2026-04-28 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
