# Generated by Django 5.2.5 on 2026-05-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0002_diario_fecha_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='estado_animo',
            field=models.IntegerField(blank=True),
        ),
    ]
