# Generated by Django 5.2.5 on 2026-05-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0003_alter_diario_estado_animo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='estado_animo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
