# Generated by Django 5.2.5 on 2026-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0004_alter_diario_estado_animo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
