# Generated by Django 5.2.5 on 2026-05-04 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0006_historialsesiones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsesiones',
            name='fecha_sesion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='RelacionTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion_doctor', models.TextField(blank=True)),
                ('fecha_tareas', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tarea', models.TextField()),
                ('estado_tarea', models.CharField(choices=[('sin_hacer', 'Sin Hacer'), ('hecha', 'Hecha'), ('no_hecha', 'No Hecha')], max_length=20)),
                ('comentario_paciente', models.TextField(blank=True)),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicologiapp.relaciontareas')),
            ],
        ),
    ]
