# Generated by Django 5.2.5 on 2026-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0008_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='estado_tarea',
            field=models.CharField(choices=[('sin_hacer', 'Sin Hacer'), ('hecha', 'Hecha'), ('no_hecha', 'No Hecha')], default='sin_hacer', max_length=20),
        ),
    ]
