# Generated by Django 5.2.5 on 2026-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0009_alter_tareas_estado_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaciontareas',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
