# Generated by Django 5.2.5 on 2026-05-31 10:51

import django.db.models.deletion
import psicologiapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0011_mensaje_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=psicologiapp.models.rutaArchivos)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologiapp.diario')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologiapp.historialsesiones')),
            ],
        ),
    ]
