# Generated by Django 5.2.5 on 2026-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0012_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20),
        ),
    ]
