# Generated by Django 5.2.5 on 2026-05-31 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologiapp', '0013_alter_archivos_tipo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='psicologiapp.diario'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='psicologiapp.historialsesiones'),
        ),
    ]
